/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wsstore.workspacestore.forms;

import javax.swing.JDialog;

/**
 *
 * @author avj02
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnAbrir = new javax.swing.JMenu();
        mnAbrirCliente = new javax.swing.JMenu();
        mnAbrirClienteCadastro = new javax.swing.JMenuItem();
        mnAbrirLivros = new javax.swing.JMenu();
        mnAbrirLivrosCadastro = new javax.swing.JMenuItem();
        mnSistema = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gerenciamento de Dados");

        mnAbrir.setText("Abrir");

        mnAbrirCliente.setText("Cliente");

        mnAbrirClienteCadastro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnAbrirClienteCadastro.setText("Cadastro");
        mnAbrirClienteCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAbrirClienteCadastroActionPerformed(evt);
            }
        });
        mnAbrirCliente.add(mnAbrirClienteCadastro);

        mnAbrir.add(mnAbrirCliente);

        mnAbrirLivros.setText("Livros");
        mnAbrirLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAbrirLivrosActionPerformed(evt);
            }
        });

        mnAbrirLivrosCadastro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnAbrirLivrosCadastro.setText("Cadastro");
        mnAbrirLivrosCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAbrirLivrosCadastroActionPerformed(evt);
            }
        });
        mnAbrirLivros.add(mnAbrirLivrosCadastro);

        mnAbrir.add(mnAbrirLivros);

        jMenuBar1.add(mnAbrir);

        mnSistema.setText("Sistema");
        jMenuBar1.add(mnSistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnAbrirClienteCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAbrirClienteCadastroActionPerformed
        openForm(new FormCliente());
    }//GEN-LAST:event_mnAbrirClienteCadastroActionPerformed

    private void mnAbrirLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAbrirLivrosActionPerformed
     //gg
    }//GEN-LAST:event_mnAbrirLivrosActionPerformed

    private void mnAbrirLivrosCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAbrirLivrosCadastroActionPerformed
        openForm(new FormLivros());
    }//GEN-LAST:event_mnAbrirLivrosCadastroActionPerformed
    
    private void openForm(JDialog f){
        f.setModal(true);
        f.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnAbrir;
    private javax.swing.JMenu mnAbrirCliente;
    private javax.swing.JMenuItem mnAbrirClienteCadastro;
    private javax.swing.JMenu mnAbrirLivros;
    private javax.swing.JMenuItem mnAbrirLivrosCadastro;
    private javax.swing.JMenu mnSistema;
    // End of variables declaration//GEN-END:variables
}
